folio-org/mod-rtac

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/RTACResourceImpl.java
- src/test/java/org/folio/rest/impl/RTACResourceImplTest.java
- src/test/resources/RTACResourceImpl/success_holdings_3.json
- src/test/resources/RTACResourceImpl/success_instance_4.json
- src/test/resources/RTACResourceImpl/success_items_4.json
- src/test/resources/RTACResourceImpl/success_loans_6.json
- src/test/resources/RTACResourceImpl/success_rtac_response_no_dueDate.json
The RTAC "dueDate" field was being set regardless of whether or not the field was set in the loan. If "dueDate" was not set in the loan, mod-rtac set it to the current date, due to the field being "null" when extracted from the loan. Now, if "dueDate" is not set in the loan, mod-rtac will not set "dueDate" in the response JSON.
> Due date bugfix

- descriptors/ModuleDescriptor-template.json
- ramls/holding.json
- src/main/java/org/folio/rest/impl/RTACResourceImpl.java
- src/test/java/org/folio/rest/impl/RTACResourceImplTest.java
- src/test/resources/RTACResourceImpl/success_items_1.json
- src/test/resources/RTACResourceImpl/success_items_2.json
- src/test/resources/RTACResourceImpl/success_items_4.json
- src/test/resources/RTACResourceImpl/success_rtac_response.json
- src/test/resources/RTACResourceImpl/success_rtac_response_no_dueDate.json
The inventory interface introduced breaking changes that require users to get the current location of an item from the new "effectiveLocation" field. Items returned by inventory interface now have their own "permanentLocation" and "temporaryLocation" which are no longer inherited from the holdings record. Since we use those fields, which are now all unset/null, the "location" is no longer returned by rtac.
This change removes "tempLocation", which is no longer relevant, and uses "effecitveLocation" instead of the item's "permanentLocation". The rtac interface has also been updated to require inventory 5.3 and the rtac interface has been increased to 1.1. The interface has also been renamed from "mod-rtac" to "rtac", which is how most modules have declared their interfaces.
Since the …
> Fixes for inventory item "location" changes

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/RTACResourceImpl.java
- src/test/java/org/folio/rest/impl/RTACResourceImplTest.java
- MODRTAC-1: Updated the issues link in the POM file to point to the MODRTAC Jira project instead of the FOLIO project. The MODRTAC Jira project was added after the last mod-rtac release.
- MODRTAC-2: Updated the `limit` query parameter to `Integer.MAX_VALUE` when retrieving RTAC data from other modules. The old limit was `100`.
> Fixes for MODRTAC-1 and MODRTAC-2

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/holding.json
- ramls/holdings.json
Version 5.0 of circulation is now available. Updated mod-rtac to be able to support this version. Also added descriptions to missing JSON schema entries.
> Fixes for MODRTAC-5 and MODRTAC-6

- descriptors/ModuleDescriptor-template.json
Can be included in the multiple support list as the only endpoint used is the loans collection which is unaffected by the changes in 6.0
> Include 6.0 in supported circulation versions MODRTAC-11

- descriptors/ModuleDescriptor-template.json
As the only endpoint used is the loans collection which is unaffected by the changes in 7.0
> Include 7.0 in supported circulation versions MODRTAC-12

- pom.xml
The CI/CD pipeline does multiple maven builds per job. One of these builds includes `-DskipTests`. This causes the `maven-dependency-plugin` to issue the following warning:
```
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (analyze) @ mod-rtac ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.aspectj:aspectjrt:jar:1.8.9:compile
```
We have the plugin configured to fail the build on warnings, which is a good thing, I think, since most build warnings are ignored and can be easily fixed, like this one.
The problem here, is we have declared `aspectjrt` as an explicit, compile time, dependency when it is not. During the regular build, when the unit tests are executed, the `aspectjrt` dependency is loaded as RMB dependencies use aspectj for data validation and possibly …
> Add runtime scope to the aspectjrt dependency

- descriptors/ModuleDescriptor-template.json
**Have to be merged with**: https://github.com/folio-org/mod-inventory-storage/pull/338
> MODRTAC-20, MODINVSTOR-364: Update holdings-storage API version to 4.0.

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
> MODRTAC-24 FOLIO-2358 manage container memory

- pom.xml
The latest version requires some updates to existing versions in order to satisfy the dependency check plugin. Updated a few other dependencies.
> MODRTAC-25: update RMB and dependencies that have changed

- descriptors/ModuleDescriptor-template.json
- src/test/resources/RTACResourceImpl/success_items_1.json
- src/test/resources/RTACResourceImpl/success_items_2.json
- src/test/resources/RTACResourceImpl/success_items_4.json
- src/test/resources/RTACResourceImpl/success_items_5.json
https://issues.folio.org/browse/MODRTAC-28: Migrate to new major version of item-storage, inventory, circulation.
Migrate to inventory:10.0 and circulation:9.0.
Changes:
Changes:
1. `item.status.name` has restricted to the following values:
* Available
* Awaiting pickup
* Awaiting delivery
* Checked out
* In process
* In transit
* Missing
* On order
* Paged
* Withdrawn
* Declared lost
2. *Item.status* and *item.status.name* are required now, no defaulting available anymore;
3. Array *item.copyNumbers* converted to a single value *copyNumber*;
4. Item.status.date is read-only field now and has date-time formatting now ("yyyy-MM-dd'T'HH:mm:ss.SSS+0000").
1. Array *request.item.copyNumbers* has converted to a single value - *copyNumber*;
2. *request/loan.item.status.date* has date-time …
> MODRTAC-28: Migrate to inventory v10.0 and circulation v9.0.

- pom.xml
- src/main/java/org/folio/rest/impl/RtacResourceImpl.java
- src/test/java/org/folio/rest/impl/ErrorConditionsTests.java
- src/test/java/org/folio/rest/impl/RtacResourceImplTest.java
* Upgrade maven-checkstyle-plugin from 3.1.0 to 3.1.1
* Upgrade com.puppycrawl.tools:checkstyle from 8.26 to 8.29
by using the default shipped with maven-checkstyle-plugin:3.1.1
* A new goole_checks.xml is shipped with new maven-checkstyle-plugin version
that warns about these whitespace issues that this PR also fixes:
* (imports) CustomImportOrder: Extra separation in import group before …
* (indentation) Indentation: 'method call' child has incorrect indentation level
> MODRTAC-31: Checkstyle security vulnerability, upgrade to 3.1.1 + 8.29

- pom.xml
- ramls/examples/rtac-request.sample
- ramls/inventory-hierarchy/inventory-instance-records.json
- ramls/rtac-request.json
- src/main/java/org/folio/clients/CirculationClient.java
- src/main/java/org/folio/clients/FolioFacade.java
- src/main/java/org/folio/clients/InventoryClient.java
- src/main/java/org/folio/mappers/FolioToRtacMapper.java
- src/main/java/org/folio/rest/impl/RtacBatchResourceImpl.java
- src/test/java/org/folio/mappers/FolioToRtacMapperTest.java
- src/test/java/org/folio/rest/impl/MockData.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/RtacBatchResourceImplTest.java
Better handle periodicals in response
Using https://github.com/folio-org/mod-rtac/pull/46 as a baseline. Adding support for a new parameter "fullPeriodicals". 
*    if it’s set to “true”, then item-level information is added to all periodicals without holdings-level information,
*    if it’s set to “false” or not defined, then holding-level information replaces item-level for periodicals.
Jira: https://issues.folio.org/browse/MODRTAC-37
Jira: https://issues.folio.org/browse/MODRTAC-38
> Better handle periodicals in response

- NEWS.md
- pom.xml
There is no version 33.0.0 for plugin 'domain-models-interface-extensions', so still use 32.1.0
> MODRTAC-58 Upgrade to RAML Module Builder 33.x

- NEWS.md
- src/main/java/org/folio/clients/CirculationClient.java
- src/main/java/org/folio/mappers/FolioToRtacMapper.java
- src/test/java/org/folio/rest/impl/MockData.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/RtacBatchResourceImplTest.java
The overarching problem here was that mod-rtac has been written on the
assumption that instances cannot have holdings records without also 
having item records.  The error noted in the issue was coming from the
code that looks up loan data for item records-it was being passed holdings
data without item data, and was attempting to look for loan data on 
non-existent items.  I put in a check there to exit 
if there were no item records to look up.  The code that maps the data 
to the RTAC response also needed to be reworked, because it needed 
to take the possibility of there being holdings but no items into account when 
deciding how to map data and what to return.  That code may need some
refactoring-I tried to be as concise as possible but there's a lot of variables that
need to be …
> MODRTAC-56 If fullPeriodicals = false then always return holdings information

- NEWS.md
- pom.xml
Resolve CVE-2021-44228 as per [MODRTAC-81](https://issues.folio.org/browse/MODRTAC-81).
> MODRTAC-81: Upgrade to Log4J 2.16.0 (Kiwi R3 2021).

- NEWS.md
- pom.xml
Resolve CVE-2021-44228 as per [MODRTAC-83](https://issues.folio.org/browse/MODRTAC-83).
> MODRTAC-83: Upgrade to Log4J 2.16.0 (Juniper R2 2021)

- NEWS.md
- pom.xml
Resolve CVE-2021-44228 as per [MODRTAC-81](https://issues.folio.org/browse/MODRTAC-81).
> MODRTAC-81: Upgrade to Log4J 2.16.0 (Lotus).

- NEWS.md
- pom.xml
- src/test/java/org/folio/clients/InventoryClientTests.java
I had some test failures in master that I recognized as being due to
a port binding conflict.  This is why I've changed some of the test code
to use a dynamic port assignment.
> MODRTAC-86: upgrading to RMB 33.2.4

- pom.xml
https://issues.folio.org/browse/MODRTAC-93
The log4j fails due to an exception at shutdown.
The 2.16.0 version of `log4j-bom` pulls in the dependencies that have the CVEs:
- [CVE-2021-45105](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105)
- [CVE-2021-44832](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832)
Replace the managed `log4j-bom` with 2.17.2 to fix this problem and ensure the version with the CVE is never used in any manner.
I went with RMB 33.2.0 instead of 34.0.0 due to problems.
see: https://issues.apache.org/jira/browse/LOG4J2-1618
see: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-bom/2.16.0
> MODRTAC-93 Upgrade to RMB 33.2.10.

- pom.xml
*Purpose*
I encountered persistent issues with local builds due to AspectJ libraries not being found on the classpath.
Using the configuration from mod-usrers, which removes the build dependency and moves the dependency solely to the plugin seems to resolve this.
> Specify AspectJ plugin dependencies MODRTAC-93

- src/main/java/org/folio/clients/FolioFacade.java
- src/main/java/org/folio/mappers/ErrorMapper.java
- src/test/java/org/folio/rest/impl/RtacBatchResourceImplTest.java
I modified the code in folioFacade that forms the response to requests.
I also modified the errorMapper class so that there are two separate error
messages for no holdings and no instance found.
Finally, I modified and created new tests to check for the new error messages.
> MODRTAC-88: Separate error message for not found instances

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODRTAC-99
> MODRTAC-99: Upgrade to RAML Module Builder 35.x.x.

- PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/MODRTAC-96
This module involves Items, Loans, and Holdings but none of the personal data is being pulled in or transferred in regards to these.
The notes fields from the Holdings are being pulled in and are being mapped into the "Status" field. These notes do get transmitted and so I consider this falls within the "stores fields with free-form text" under the prescribed definition of "store" (see mapHoldingStatements() and fromHoldingToRtacHolding() in FolioToRtacMapper.java). The "Statement" from the note is pulled in and this appears to be free-form text.
> MODRTAC-96: Add personal data disclosure form.

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- ramls/rtac.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODRTAC-103 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- ramls/inventory-hierarchy/inventory-instance-records.json
- src/main/java/org/folio/mappers/FolioToRtacMapper.java
- src/test/java/org/folio/mappers/FolioToRtacMapperTest.java
- src/test/java/org/folio/rest/impl/RtacBatchResourceImplTest.java
- src/test/resources/mock-data/inventory-view/test_instance_with_holding_and_item.json
Purpose:
https://folio-org.atlassian.net/browse/MODRTAC-107
Related inventory-storage PR: https://github.com/folio-org/mod-inventory-storage/pull/985/files
How it works when displaySummary is populated:
Hot it works when other field populated like enumeration, chronology:
The same is for deperecated endoint Get rtac by id
> [MODRTAC-107]. Add new displaySummarry field

- ramls/inventory-hierarchy/inventory-instance-records.json
- ramls/rtac-holding.json
- src/main/java/org/folio/mappers/FolioToRtacMapper.java
- src/test/java/org/folio/rest/impl/RtacBatchResourceImplTest.java
- src/test/resources/mock-data/inventory-view/test_instance_with_holding_and_item.json
Add holdings and itemCopyNumber to rtac response
[jira ticket](https://folio-org.atlassian.net/browse/EDGRTAC-81)
- Change FolioRtacMapper to add holdingsCopyNumber and itemCopyNumber
> Add holdingsCopyNumber and itemCopyNumber to rtac response

- pom.xml
Maven plugin for validating FOLIO module descriptors. It checks the module descriptor template placed in FOLIO modules for issues and ensures it adheres to FOLIO common approach.
- Repo for ref: https://github.com/folio-org/folio-module-descriptor-validator
> Pom.xml - added validation for descriptor files

- pom.xml
- Update RMB dependency to v35.3.0
- Update Vertx dependency to v4.5.10
https://folio-org.atlassian.net/browse/MODRTAC-115
> MODRTAC-115: Update Vert.x to v4.5.10 version and RMB dependency to v35.3.0

- src/main/java/org/folio/mappers/FolioToRtacMapper.java
- src/test/java/org/folio/rest/impl/RtacBatchResourceImplTest.java
- src/test/resources/mock-data/pieces/piece_collection.json
[MODRTAC-123](https://folio-org.atlassian.net/browse/MODRTAC-123): Show display summary info for pieces without items
> MODRTAC-123: Add piece copy number to holdings
